### ISSUE TITLE
No badge on the readme

### ISSUE THREAD

**Issue by bianchigg** [RoadSplash/python-intermediate-rivercatchment#10]
this is pretty criminal. You should have as many badges as possible to glam up your repo.

**Comment by AAAmali** [comment]
We don't know how to be less criminal. Please show us the way.
![GruReflectionGIF](https://user-images.githubusercontent.com/59627840/229101252-1bc8691e-8858-49c8-82ff-d1a20ec32ca8.gif)

**Comment by bianchigg** [comment]
A badge has appeared on the readme. All the charges have been dropped.
